[package]
name = "path-traversal-directory-tree"
version = "0.1.0"
edition = "2021"
authors = ["Henrique Torquato"]

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
curl = "0.4.47"
linereader = "0.4.0"
url = "2.5.4"
urlencoding = "2.1.3"
